"""initial schema

Revision ID: 9b3583ffc747
Revises: 
Create Date: 2026-07-12 02:44:23.434563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3583ffc747'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('record_type', sa.String(length=60), nullable=True),
    sa.Column('record_id', sa.String(length=40), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('session_info', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('global_document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trading_name', sa.String(length=255), nullable=True),
    sa.Column('business_registration_number', sa.String(length=100), nullable=True),
    sa.Column('tin', sa.String(length=50), nullable=True),
    sa.Column('mcag_membership_number', sa.String(length=50), nullable=True),
    sa.Column('bog_licence_reference', sa.String(length=100), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('digital_address', sa.String(length=50), nullable=True),
    sa.Column('area_of_operation', sa.Text(), nullable=True),
    sa.Column('phone_primary', sa.String(length=30), nullable=True),
    sa.Column('phone_secondary', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_document_id', sa.Integer(), nullable=True),
    sa.Column('proprietor_name', sa.String(length=255), nullable=True),
    sa.Column('manager_name', sa.String(length=255), nullable=True),
    sa.Column('date_operations_commenced', sa.Date(), nullable=True),
    sa.Column('principal_bank', sa.String(length=255), nullable=True),
    sa.Column('bank_account_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account_number', sa.String(length=80), nullable=True),
    sa.Column('dpc_registration', sa.String(length=120), nullable=True),
    sa.Column('credit_bureau_relationship', sa.String(length=255), nullable=True),
    sa.Column('auditor_name', sa.String(length=255), nullable=True),
    sa.Column('accountant_name', sa.String(length=255), nullable=True),
    sa.Column('regulatory_renewal_date', sa.Date(), nullable=True),
    sa.Column('mcag_renewal_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('next_customer_seq', sa.Integer(), nullable=False),
    sa.Column('next_application_seq', sa.Integer(), nullable=False),
    sa.Column('next_loan_seq', sa.Integer(), nullable=False),
    sa.Column('next_receipt_seq', sa.Integer(), nullable=False),
    sa.Column('next_complaint_seq', sa.Integer(), nullable=False),
    sa.Column('next_journal_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_status'), ['status'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('subtype', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='uq_account_code_per_institution')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_subtype'), ['subtype'], unique=False)

    op.create_table('loan_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('min_tenure', sa.Integer(), nullable=False),
    sa.Column('max_tenure', sa.Integer(), nullable=False),
    sa.Column('repayment_frequency', sa.String(length=20), nullable=False),
    sa.Column('interest_method', sa.String(length=30), nullable=False),
    sa.Column('schedule_type', sa.String(length=30), nullable=False),
    sa.Column('min_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('max_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('rate_period', sa.String(length=10), nullable=False),
    sa.Column('application_fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('processing_fee_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('processing_fee_fixed', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_fees', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fees_deducted_upfront', sa.Boolean(), nullable=False),
    sa.Column('penalty_basis', sa.String(length=30), nullable=False),
    sa.Column('penalty_rate_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('penalty_fixed_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('penalty_grace_days', sa.Integer(), nullable=False),
    sa.Column('penalty_max_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('early_settlement_charge_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('early_settlement_terms', sa.Text(), nullable=True),
    sa.Column('grace_periods', sa.Integer(), nullable=False),
    sa.Column('guarantors_required', sa.Integer(), nullable=False),
    sa.Column('collateral_required', sa.Boolean(), nullable=False),
    sa.Column('required_documents', sa.Text(), nullable=True),
    sa.Column('approval_authority', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'code', name='uq_product_code_per_institution')
    )
    with op.batch_alter_table('loan_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_products_institution_id'), ['institution_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_institution_id'), ['institution_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active_user', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('approval_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_institution_id'), ['institution_id'], unique=False)

    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('cashbook_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_date', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_receipts', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_disbursements', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('expenses', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_handed_over', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_banked', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('physical_count', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('prepared_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['prepared_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'book_date', name='uq_cashbook_day_per_institution')
    )
    with op.batch_alter_table('cashbook_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashbook_days_book_date'), ['book_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashbook_days_institution_id'), ['institution_id'], unique=False)

    op.create_table('collection_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('zone_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_zone_name_per_institution')
    )
    with op.batch_alter_table('collection_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_zones_institution_id'), ['institution_id'], unique=False)

    op.create_table('credit_bureau_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bureau_name', sa.String(length=120), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('correction_notes', sa.Text(), nullable=True),
    sa.Column('dispute_status', sa.String(length=120), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_bureau_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_bureau_submissions_institution_id'), ['institution_id'], unique=False)

    op.create_table('data_breach_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('discovered_on', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_affected', sa.Text(), nullable=True),
    sa.Column('persons_affected', sa.Integer(), nullable=True),
    sa.Column('containment_actions', sa.Text(), nullable=True),
    sa.Column('reported_to_dpc', sa.Boolean(), nullable=False),
    sa.Column('dpc_report_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_breach_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_breach_records_institution_id'), ['institution_id'], unique=False)

    op.create_table('funding_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('repayment_terms', sa.Text(), nullable=True),
    sa.Column('security_given', sa.String(length=255), nullable=True),
    sa.Column('outstanding_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('funding_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funding_sources_institution_id'), ['institution_id'], unique=False)

    op.create_table('guarantors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('relationship_to_borrower', sa.String(length=120), nullable=True),
    sa.Column('ghana_card_number', sa.String(length=30), nullable=True),
    sa.Column('ghana_card_expiry_date', sa.Date(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('residence', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('employer_or_business', sa.String(length=200), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_guaranteed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guarantors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guarantors_ghana_card_number'), ['ghana_card_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_guarantors_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guarantors_phone'), ['phone'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_number', sa.String(length=30), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('reversed_entry_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversed_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'journal_number', name='uq_journal_number_per_institution')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_institution_id'), ['institution_id'], unique=False)

    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_attempted', sa.String(length=255), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_events_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_events_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('support_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('raised_by_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_requests_institution_id'), ['institution_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=120), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('home_town', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('ghana_card_number', sa.String(length=30), nullable=True),
    sa.Column('ghana_card_issue_date', sa.Date(), nullable=True),
    sa.Column('ghana_card_expiry_date', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('dependants', sa.Integer(), nullable=True),
    sa.Column('phone_primary', sa.String(length=30), nullable=True),
    sa.Column('phone_secondary', sa.String(length=30), nullable=True),
    sa.Column('cycle_number', sa.Integer(), nullable=True),
    sa.Column('ethnicity', sa.String(length=80), nullable=True),
    sa.Column('religion', sa.String(length=80), nullable=True),
    sa.Column('place_of_worship', sa.String(length=120), nullable=True),
    sa.Column('worship_location', sa.String(length=120), nullable=True),
    sa.Column('worship_leader', sa.String(length=120), nullable=True),
    sa.Column('house_number', sa.String(length=60), nullable=True),
    sa.Column('residential_digital_address', sa.String(length=40), nullable=True),
    sa.Column('residential_location', sa.String(length=200), nullable=True),
    sa.Column('residential_landmark', sa.String(length=200), nullable=True),
    sa.Column('years_at_residence', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('accommodation_status', sa.String(length=30), nullable=True),
    sa.Column('landlord_name', sa.String(length=200), nullable=True),
    sa.Column('rent_expiry_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('business_type', sa.String(length=120), nullable=True),
    sa.Column('business_location', sa.String(length=200), nullable=True),
    sa.Column('business_landmark', sa.String(length=200), nullable=True),
    sa.Column('years_in_business', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('years_at_business_location', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('premises_type', sa.String(length=60), nullable=True),
    sa.Column('premises_status', sa.String(length=60), nullable=True),
    sa.Column('estimated_daily_sales', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('estimated_daily_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('estimated_working_capital', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('number_of_employees', sa.Integer(), nullable=True),
    sa.Column('other_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('employer_name', sa.String(length=200), nullable=True),
    sa.Column('employer_location', sa.String(length=200), nullable=True),
    sa.Column('employer_business_type', sa.String(length=120), nullable=True),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('years_employed', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('net_monthly_salary', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('bank_branch', sa.String(length=120), nullable=True),
    sa.Column('bank_account_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account_number', sa.String(length=60), nullable=True),
    sa.Column('momo_provider', sa.String(length=40), nullable=True),
    sa.Column('momo_number', sa.String(length=30), nullable=True),
    sa.Column('momo_name', sa.String(length=200), nullable=True),
    sa.Column('household_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('household_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('existing_monthly_repayments', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source_of_repayment', sa.String(length=255), nullable=True),
    sa.Column('existing_loans_details', sa.Text(), nullable=True),
    sa.Column('spouse_name', sa.String(length=200), nullable=True),
    sa.Column('spouse_phone', sa.String(length=30), nullable=True),
    sa.Column('spouse_occupation', sa.String(length=120), nullable=True),
    sa.Column('next_of_kin_name', sa.String(length=200), nullable=True),
    sa.Column('next_of_kin_relationship', sa.String(length=80), nullable=True),
    sa.Column('next_of_kin_phone', sa.String(length=30), nullable=True),
    sa.Column('next_of_kin_address', sa.String(length=255), nullable=True),
    sa.Column('relatives_info', sa.Text(), nullable=True),
    sa.Column('references_info', sa.Text(), nullable=True),
    sa.Column('collection_zone_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_zone_id'], ['collection_zones.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'customer_number', name='uq_customer_number_per_institution')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_bank_account_number'), ['bank_account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_customer_number'), ['customer_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_ghana_card_number'), ['ghana_card_number'], unique=False)
        batch_op.create_index('ix_customers_inst_ghana_card', ['institution_id', 'ghana_card_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_momo_number'), ['momo_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone_primary'), ['phone_primary'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('paid_from_subtype', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payee', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_institution_id'), ['institution_id'], unique=False)

    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_lines_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_journal_entry_id'), ['journal_entry_id'], unique=False)

    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('complainant_name', sa.String(length=255), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('date_resolved', sa.Date(), nullable=True),
    sa.Column('customer_informed', sa.Boolean(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalation_details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'complaint_number', name='uq_complaint_number_per_institution')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)

    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=60), nullable=False),
    sa.Column('given', sa.Boolean(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_records_institution_id'), ['institution_id'], unique=False)

    op.create_table('data_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=30), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_requests_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_requests_institution_id'), ['institution_id'], unique=False)

    op.create_table('duplicate_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('related_record_type', sa.String(length=60), nullable=True),
    sa.Column('related_record_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duplicate_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duplicate_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_alerts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_alerts_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_alerts_status'), ['status'], unique=False)

    op.create_table('loan_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_number', sa.String(length=30), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('loan_purpose', sa.String(length=255), nullable=False),
    sa.Column('purpose_sector', sa.String(length=80), nullable=True),
    sa.Column('amount_requested', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('proposed_tenure', sa.Integer(), nullable=False),
    sa.Column('repayment_frequency', sa.String(length=20), nullable=False),
    sa.Column('proposed_payment_method', sa.String(length=30), nullable=True),
    sa.Column('proposed_collateral', sa.Text(), nullable=True),
    sa.Column('application_fee_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('receiving_officer_id', sa.Integer(), nullable=True),
    sa.Column('declaration_accepted', sa.Boolean(), nullable=False),
    sa.Column('signed_by', sa.String(length=20), nullable=True),
    sa.Column('date_signed', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('approved_tenure', sa.Integer(), nullable=True),
    sa.Column('approved_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('approval_conditions', sa.Text(), nullable=True),
    sa.Column('reduction_reason', sa.Text(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('policy_exceptions', sa.Text(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['loan_products.id'], ),
    sa.ForeignKeyConstraint(['receiving_officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'application_number', name='uq_app_number_per_institution')
    )
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_applications_application_number'), ['application_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_applications_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_applications_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_applications_status'), ['status'], unique=False)

    op.create_table('application_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_status_history_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_status_history_institution_id'), ['institution_id'], unique=False)

    op.create_table('credit_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('daily_sales', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('monthly_sales', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_of_sales', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('operating_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('household_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('existing_loan_repayments', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_commitments', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_disposable_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('proposed_instalment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('repayment_surplus', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('instalment_to_income_percent', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('debt_service_ratio_percent', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('residence_stability', sa.String(length=255), nullable=True),
    sa.Column('years_in_business_confirmed', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('previous_repayment_history', sa.Text(), nullable=True),
    sa.Column('supplier_references', sa.Text(), nullable=True),
    sa.Column('community_references', sa.Text(), nullable=True),
    sa.Column('credit_bureau_history', sa.Text(), nullable=True),
    sa.Column('information_accuracy', sa.String(length=255), nullable=True),
    sa.Column('officer_observations', sa.Text(), nullable=True),
    sa.Column('working_capital', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('stock_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('business_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('business_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('profitability', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('seasonality', sa.Text(), nullable=True),
    sa.Column('business_risks', sa.Text(), nullable=True),
    sa.Column('owner_contribution', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_recommended', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tenure_recommended', sa.Integer(), nullable=True),
    sa.Column('frequency_recommended', sa.String(length=20), nullable=True),
    sa.Column('rate_recommended', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('risk_rating', sa.String(length=20), nullable=True),
    sa.Column('recommendation', sa.String(length=30), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_assessments_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_assessments_institution_id'), ['institution_id'], unique=False)

    op.create_table('field_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('visit_time', sa.String(length=10), nullable=True),
    sa.Column('residence_visited', sa.Boolean(), nullable=True),
    sa.Column('business_visited', sa.Boolean(), nullable=True),
    sa.Column('gps_consent', sa.Boolean(), nullable=True),
    sa.Column('gps_location', sa.String(length=80), nullable=True),
    sa.Column('digital_address', sa.String(length=40), nullable=True),
    sa.Column('business_activity_observed', sa.Text(), nullable=True),
    sa.Column('stock_observed', sa.Text(), nullable=True),
    sa.Column('employees_observed', sa.Integer(), nullable=True),
    sa.Column('estimated_sales', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('estimated_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('business_operating_days', sa.Integer(), nullable=True),
    sa.Column('premises_status', sa.String(length=80), nullable=True),
    sa.Column('landlord_verification', sa.Text(), nullable=True),
    sa.Column('residence_verification', sa.Text(), nullable=True),
    sa.Column('collateral_sighted', sa.Boolean(), nullable=True),
    sa.Column('officer_comments', sa.Text(), nullable=True),
    sa.Column('recommended_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('recommended_tenure', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_verifications_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_verifications_institution_id'), ['institution_id'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_number', sa.String(length=30), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('rate_period', sa.String(length=10), nullable=False),
    sa.Column('interest_method', sa.String(length=30), nullable=False),
    sa.Column('schedule_type', sa.String(length=30), nullable=False),
    sa.Column('repayment_frequency', sa.String(length=20), nullable=False),
    sa.Column('tenure', sa.Integer(), nullable=False),
    sa.Column('grace_periods', sa.Integer(), nullable=False),
    sa.Column('total_interest', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_repayment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('apr', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('first_due_date', sa.Date(), nullable=True),
    sa.Column('final_due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('written_off_at', sa.DateTime(), nullable=True),
    sa.Column('write_off_reason', sa.Text(), nullable=True),
    sa.Column('write_off_requested_by_id', sa.Integer(), nullable=True),
    sa.Column('write_off_approved_by_id', sa.Integer(), nullable=True),
    sa.Column('principal_outstanding', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_outstanding', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('penalties_outstanding', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('restructured_from_id', sa.Integer(), nullable=True),
    sa.Column('purpose_sector', sa.String(length=80), nullable=True),
    sa.Column('collection_zone_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['collection_zone_id'], ['collection_zones.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['loan_products.id'], ),
    sa.ForeignKeyConstraint(['restructured_from_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['write_off_approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['write_off_requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'loan_number', name='uq_loan_number_per_institution')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_loan_number'), ['loan_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_status'), ['status'], unique=False)

    op.create_table('collaterals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('collateral_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_relationship', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('estimated_market_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('forced_sale_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valuation_date', sa.Date(), nullable=True),
    sa.Column('valuer', sa.String(length=200), nullable=True),
    sa.Column('proof_of_ownership', sa.String(length=255), nullable=True),
    sa.Column('existing_encumbrances', sa.Text(), nullable=True),
    sa.Column('insurance_details', sa.String(length=255), nullable=True),
    sa.Column('registration_details', sa.String(length=255), nullable=True),
    sa.Column('collateral_registry_reference', sa.String(length=120), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('enforcement_status', sa.String(length=30), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collaterals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collaterals_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaterals_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaterals_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collaterals_loan_id'), ['loan_id'], unique=False)

    op.create_table('guarantee_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guarantor_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('guaranteed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('date_signed', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['guarantor_id'], ['guarantors.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guarantee_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guarantee_links_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guarantee_links_guarantor_id'), ['guarantor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guarantee_links_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guarantee_links_loan_id'), ['loan_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_loan_id'), ['loan_id'], unique=False)

    op.create_table('loan_restructures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_loan_id', sa.Integer(), nullable=False),
    sa.Column('new_loan_id', sa.Integer(), nullable=True),
    sa.Column('restructure_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('customer_request_reference', sa.String(length=255), nullable=True),
    sa.Column('old_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('new_terms', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credit_bureau_treatment', sa.String(length=120), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['new_loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['original_loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_restructures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_restructures_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_restructures_new_loan_id'), ['new_loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_restructures_original_loan_id'), ['original_loan_id'], unique=False)

    op.create_table('recovery_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('promised_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('promise_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.String(length=255), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_actions_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recovery_actions_loan_id'), ['loan_id'], unique=False)

    op.create_table('repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('collection_zone_id', sa.Integer(), nullable=True),
    sa.Column('allocated_principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allocated_interest', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allocated_penalties', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allocated_fees', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reversed', sa.Boolean(), nullable=False),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('reversal_requested_by_id', sa.Integer(), nullable=True),
    sa.Column('reversal_approved_by_id', sa.Integer(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_zone_id'], ['collection_zones.id'], ),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['reversal_approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversal_requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'receipt_number', name='uq_receipt_number_per_institution')
    )
    with op.batch_alter_table('repayments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repayments_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repayments_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repayments_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_repayments_receipt_number'), ['receipt_number'], unique=False)

    op.create_table('schedule_instalments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('opening_principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('principal_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fees_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('penalties_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fees_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('penalties_paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('closing_principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'number', name='uq_instalment_number_per_loan')
    )
    with op.batch_alter_table('schedule_instalments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_instalments_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_instalments_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_instalments_loan_id'), ['loan_id'], unique=False)

    op.create_table('settlement_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('principal_outstanding', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_accrued', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('early_settlement_charge', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('penalties', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('waivers', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_settlement', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_quotes_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_quotes_loan_id'), ['loan_id'], unique=False)

    op.create_table('waivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('waiver_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waivers_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waivers_loan_id'), ['loan_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=80), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('loan_application_id', sa.Integer(), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('guarantor_id', sa.Integer(), nullable=True),
    sa.Column('collateral_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collateral_id'], ['collaterals.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['guarantor_id'], ['guarantors.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_collateral_id'), ['collateral_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_guarantor_id'), ['guarantor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_loan_application_id'), ['loan_application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)

    op.create_table('credit_bureau_enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_date', sa.Date(), nullable=True),
    sa.Column('bureau_name', sa.String(length=120), nullable=False),
    sa.Column('enquiry_date', sa.Date(), nullable=False),
    sa.Column('report_reference', sa.String(length=120), nullable=True),
    sa.Column('report_document_id', sa.Integer(), nullable=True),
    sa.Column('existing_facilities', sa.Text(), nullable=True),
    sa.Column('outstanding_balances', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('arrears', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('defaults_found', sa.Boolean(), nullable=True),
    sa.Column('officer_comments', sa.Text(), nullable=True),
    sa.Column('impact_on_decision', sa.String(length=255), nullable=True),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_bureau_enquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_bureau_enquiries_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_bureau_enquiries_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_bureau_enquiries_institution_id'), ['institution_id'], unique=False)

    op.create_table('disbursements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('gross_principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fees_deducted', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fees_paid_separately', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('disbursement_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('bank_account', sa.String(length=120), nullable=True),
    sa.Column('momo_number', sa.String(length=30), nullable=True),
    sa.Column('cheque_details', sa.String(length=120), nullable=True),
    sa.Column('payment_reference', sa.String(length=120), nullable=True),
    sa.Column('initiated_by_id', sa.Integer(), nullable=False),
    sa.Column('authorised_by_id', sa.Integer(), nullable=True),
    sa.Column('authorised_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_document_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorised_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disbursements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disbursements_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disbursements_loan_id'), ['loan_id'], unique=False)

    op.create_table('mcag_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('proof_document_id', sa.Integer(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('validation_json', sa.Text(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['locked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proof_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'period', name='uq_mcag_return_period')
    )
    with op.batch_alter_table('mcag_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcag_returns_institution_id'), ['institution_id'], unique=False)

    op.create_table('offer_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('offer_number', sa.String(length=30), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.Column('offer_expiry_date', sa.Date(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('signed_document_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('calculation_json', sa.Text(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['signed_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offer_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offer_letters_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_letters_institution_id'), ['institution_id'], unique=False)

    op.create_table('loan_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('agreement_date', sa.Date(), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('language_explained', sa.String(length=60), nullable=True),
    sa.Column('witness_name', sa.String(length=200), nullable=True),
    sa.Column('witness_phone', sa.String(length=30), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_document_id', sa.Integer(), nullable=True),
    sa.Column('calculation_json', sa.Text(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer_letters.id'], ),
    sa.ForeignKeyConstraint(['signed_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_agreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_agreements_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_agreements_institution_id'), ['institution_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_agreements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_agreements_institution_id'))
        batch_op.drop_index(batch_op.f('ix_loan_agreements_application_id'))

    op.drop_table('loan_agreements')
    with op.batch_alter_table('offer_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_letters_institution_id'))
        batch_op.drop_index(batch_op.f('ix_offer_letters_application_id'))

    op.drop_table('offer_letters')
    with op.batch_alter_table('mcag_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcag_returns_institution_id'))

    op.drop_table('mcag_returns')
    with op.batch_alter_table('disbursements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disbursements_loan_id'))
        batch_op.drop_index(batch_op.f('ix_disbursements_institution_id'))

    op.drop_table('disbursements')
    with op.batch_alter_table('credit_bureau_enquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_bureau_enquiries_institution_id'))
        batch_op.drop_index(batch_op.f('ix_credit_bureau_enquiries_customer_id'))
        batch_op.drop_index(batch_op.f('ix_credit_bureau_enquiries_application_id'))

    op.drop_table('credit_bureau_enquiries')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_documents_loan_id'))
        batch_op.drop_index(batch_op.f('ix_documents_loan_application_id'))
        batch_op.drop_index(batch_op.f('ix_documents_institution_id'))
        batch_op.drop_index(batch_op.f('ix_documents_guarantor_id'))
        batch_op.drop_index(batch_op.f('ix_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_documents_customer_id'))
        batch_op.drop_index(batch_op.f('ix_documents_collateral_id'))

    op.drop_table('documents')
    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waivers_loan_id'))
        batch_op.drop_index(batch_op.f('ix_waivers_institution_id'))

    op.drop_table('waivers')
    with op.batch_alter_table('settlement_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_quotes_loan_id'))
        batch_op.drop_index(batch_op.f('ix_settlement_quotes_institution_id'))

    op.drop_table('settlement_quotes')
    with op.batch_alter_table('schedule_instalments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_instalments_loan_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_instalments_institution_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_instalments_due_date'))

    op.drop_table('schedule_instalments')
    with op.batch_alter_table('repayments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repayments_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_repayments_paid_at'))
        batch_op.drop_index(batch_op.f('ix_repayments_loan_id'))
        batch_op.drop_index(batch_op.f('ix_repayments_institution_id'))

    op.drop_table('repayments')
    with op.batch_alter_table('recovery_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_actions_loan_id'))
        batch_op.drop_index(batch_op.f('ix_recovery_actions_institution_id'))

    op.drop_table('recovery_actions')
    with op.batch_alter_table('loan_restructures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_restructures_original_loan_id'))
        batch_op.drop_index(batch_op.f('ix_loan_restructures_new_loan_id'))
        batch_op.drop_index(batch_op.f('ix_loan_restructures_institution_id'))

    op.drop_table('loan_restructures')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_loan_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_institution_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_entry_date'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('guarantee_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guarantee_links_loan_id'))
        batch_op.drop_index(batch_op.f('ix_guarantee_links_institution_id'))
        batch_op.drop_index(batch_op.f('ix_guarantee_links_guarantor_id'))
        batch_op.drop_index(batch_op.f('ix_guarantee_links_application_id'))

    op.drop_table('guarantee_links')
    with op.batch_alter_table('collaterals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collaterals_loan_id'))
        batch_op.drop_index(batch_op.f('ix_collaterals_institution_id'))
        batch_op.drop_index(batch_op.f('ix_collaterals_customer_id'))
        batch_op.drop_index(batch_op.f('ix_collaterals_application_id'))

    op.drop_table('collaterals')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_status'))
        batch_op.drop_index(batch_op.f('ix_loans_loan_number'))
        batch_op.drop_index(batch_op.f('ix_loans_institution_id'))
        batch_op.drop_index(batch_op.f('ix_loans_customer_id'))

    op.drop_table('loans')
    with op.batch_alter_table('field_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_verifications_institution_id'))
        batch_op.drop_index(batch_op.f('ix_field_verifications_application_id'))

    op.drop_table('field_verifications')
    with op.batch_alter_table('credit_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_assessments_institution_id'))
        batch_op.drop_index(batch_op.f('ix_credit_assessments_application_id'))

    op.drop_table('credit_assessments')
    with op.batch_alter_table('application_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_status_history_institution_id'))
        batch_op.drop_index(batch_op.f('ix_application_status_history_application_id'))

    op.drop_table('application_status_history')
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_applications_status'))
        batch_op.drop_index(batch_op.f('ix_loan_applications_institution_id'))
        batch_op.drop_index(batch_op.f('ix_loan_applications_customer_id'))
        batch_op.drop_index(batch_op.f('ix_loan_applications_application_number'))

    op.drop_table('loan_applications')
    with op.batch_alter_table('duplicate_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duplicate_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_duplicate_alerts_institution_id'))
        batch_op.drop_index(batch_op.f('ix_duplicate_alerts_customer_id'))
        batch_op.drop_index(batch_op.f('ix_duplicate_alerts_alert_type'))

    op.drop_table('duplicate_alerts')
    with op.batch_alter_table('data_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_requests_institution_id'))
        batch_op.drop_index(batch_op.f('ix_data_requests_customer_id'))

    op.drop_table('data_requests')
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_institution_id'))
        batch_op.drop_index(batch_op.f('ix_consent_records_customer_id'))

    op.drop_table('consent_records')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_complaints_institution_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_customer_id'))

    op.drop_table('complaints')
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_lines_journal_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_institution_id'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_account_id'))

    op.drop_table('journal_lines')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_institution_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone_primary'))
        batch_op.drop_index(batch_op.f('ix_customers_momo_number'))
        batch_op.drop_index(batch_op.f('ix_customers_institution_id'))
        batch_op.drop_index('ix_customers_inst_ghana_card')
        batch_op.drop_index(batch_op.f('ix_customers_ghana_card_number'))
        batch_op.drop_index(batch_op.f('ix_customers_full_name'))
        batch_op.drop_index(batch_op.f('ix_customers_customer_number'))
        batch_op.drop_index(batch_op.f('ix_customers_bank_account_number'))

    op.drop_table('customers')
    with op.batch_alter_table('support_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_requests_institution_id'))

    op.drop_table('support_requests')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('login_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_login_events_institution_id'))

    op.drop_table('login_events')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_institution_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_date'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('guarantors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guarantors_phone'))
        batch_op.drop_index(batch_op.f('ix_guarantors_institution_id'))
        batch_op.drop_index(batch_op.f('ix_guarantors_ghana_card_number'))

    op.drop_table('guarantors')
    with op.batch_alter_table('funding_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funding_sources_institution_id'))

    op.drop_table('funding_sources')
    with op.batch_alter_table('data_breach_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_breach_records_institution_id'))

    op.drop_table('data_breach_records')
    with op.batch_alter_table('credit_bureau_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_bureau_submissions_institution_id'))

    op.drop_table('credit_bureau_submissions')
    with op.batch_alter_table('collection_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_zones_institution_id'))

    op.drop_table('collection_zones')
    with op.batch_alter_table('cashbook_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashbook_days_institution_id'))
        batch_op.drop_index(batch_op.f('ix_cashbook_days_book_date'))

    op.drop_table('cashbook_days')
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_sessions_user_id'))

    op.drop_table('active_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_institution_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_institution_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('loan_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_products_institution_id'))

    op.drop_table('loan_products')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_subtype'))
        batch_op.drop_index(batch_op.f('ix_accounts_institution_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_status'))

    op.drop_table('institutions')
    op.drop_table('global_document_templates')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_institution_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
